### ISSUE TITLE
'fail_aaguid_mismatch' even when expected guid and extracted guid from attestation logs the same. 

### ISSUE THREAD

**Issue by JinxMan25** [srinivas1729/appattest-checker-node#2]
I'm testing this on my staging environment where `developmentEnv` is set to false.

When logging `expectedGuid` and `aaGuid`, both show `appattest` but the `===` comparison fails.

Any thoughts on what could be happening?

**Comment by srinivas1729** [comment]
Can you try comparing `aaGuid.substring(0,  9)` and `expectedGuid` ?

The docs mention that `aaGuid` extracted from the attestation object will be "`appattest` followed by seven 0x00 bytes". So it may log as `appattest`, but won't match `expectedGuid`

**Comment by JinxMan25** [comment]
Yes, that worked. Shall I create a pull request to edit that?

**Comment by JinxMan25** [comment]
Any ideas why it didn't get caught in the tests?

**Comment by srinivas1729** [comment]
The tests generate fake input. But perhaps they don't fake correctly. I'll work on a fix and push it up shortly.

Thanks for reporting!

**Comment by JinxMan25** [comment]
Thank you for the prompt response! I've been testing this on my staging environment and been banging my head lol

Will push this to my production env once it's ready! Thanks.

**Comment by srinivas1729** [comment]
It turns out that my test had a bug too!  I've pushed up the [fix](https://github.com/srinivas1729/appattest-checker-node/commit/d6c8469a5ef0179cb3a6f5e2db24fab181c19f01) for code and test. I've also release v1.0.2 to NPM. Please try that version out and lmk if it works for you.

**Comment by srinivas1729** [comment]
Closing out this issue. Let me know if you have any issues.

Also, if you're open to sharing how you're using this lib, please find/message me on LinkedIn.
